[package]
name = "served"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.86"
log = "0.4.14"
test-log = "0.2.17"
env_logger = "0.11.6"
tokio = { version = "1.16.1", features = ["full"] }
once_cell = "1.20.2"
